In [9]:
import numpy as np
import pandas as pd

import plotly.express as px

In [10]:
subjects = ["soggetto_1","soggetto_2","soggetto_3","soggetto_6","soggetto_7","soggetto_8"]

In [11]:
df_weights_dict = {}
for subject in subjects:
    df_weights_dict[subject] = pd.read_csv("Datasets/{}_weights_o.csv".format(subject))
    df_weights_dict[subject].columns = ["TrRi","RiTr","Plu","Ttra","Ttrb","Tr","MeTr","MoTr","RiRi","MoFo","Mmof","MoRi","MeRi","Ri","Comp"]
    df_weights_dict[subject].index = df_weights_dict[subject].columns

In [12]:
df_free_evolution_dict = {}
for subject in subjects:
    np_matrix_initial = df_weights_dict[subject].to_numpy()
    np_matrix = np_matrix_initial
    df_free_evolution_dict[subject] = pd.DataFrame(index = ["TrRi","RiTr","Plu","Ttra","Ttrb","Tr","MeTr","MoTr","RiRi","MoFo","Mmof","MoRi","MeRi","Ri","Comp"])
    for i in range(0,20):
        np_matrix = np.matmul(np_matrix, np_matrix_initial)
        sum_np = np.sum(np_matrix, axis=1)
        df_free_evolution_dict[subject]["Epoch "+ str(i)] = pd.Series(sum_np)
        np_matrix = np.divide(np_matrix, sum_np) # divide() is division by row

    df_free_evolution_dict[subject] = df_free_evolution_dict[subject].T

In [16]:
# create test np matrix 3x3
np_matrix_test = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]])
np_matrix_test

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [17]:
# sum over rows
sum_np_test = np.sum(np_matrix_test, axis=1)
sum_np_test

array([0.6, 1.5, 2.4])

In [19]:
# divide each row by the sum of the row
np_matrix_test = np.divide(np_matrix_test, sum_np_test)
np_matrix_test

array([[0.16666667, 0.13333333, 0.125     ],
       [0.66666667, 0.33333333, 0.25      ],
       [1.16666667, 0.53333333, 0.375     ]])

In [13]:
# for every subject, plot the free evolution of the weights using plotly express
for subject in subjects:
    fig = px.line(df_free_evolution_dict[subject], title="Free evolution of the weights for subject {}".format(subject))
    fig.show()