In [177]:
import numpy as np
import pandas as pd

import plotly.express as px

In [178]:
subjects = ["soggetto_1","soggetto_2","soggetto_3","soggetto_6","soggetto_7","soggetto_8"]

In [179]:
df_weights_dict = {}
for subject in subjects:
    df_weights_dict[subject] = pd.read_csv("Datasets/{}_weights_o.csv".format(subject))
    df_weights_dict[subject].columns = ["TrRi","RiTr","Plu","Ttra","Ttrb","Tr","MeTr","MoTr","RiRi","MoFo","Mmof","MoRi","MeRi","Ri","Comp"]
    df_weights_dict[subject].index = df_weights_dict[subject].columns
    df_weights_dict[subject] = df_weights_dict[subject].T

In [180]:
df_weights_dict["soggetto_1"]

TrRi      RiTr       Plu      Ttra      Ttrb        Tr      MeTr  \
TrRi -0.770991 -0.247862  0.296357  0.183060  0.184627 -0.101070  0.283836   
RiTr -0.751945 -0.213791  0.143637  0.483585  0.094576  0.339746 -0.172645   
Plu  -0.003196 -0.263307 -0.274596  0.501303  0.255244  0.104130  0.084332   
Ttra -0.475967 -0.452790  0.401257  0.105587  0.079634  0.175691 -0.112213   
Ttrb -0.288003 -0.036305 -0.513654 -0.269760  0.433292  0.178291 -0.095082   
Tr   -0.319896 -0.265057 -0.032019  0.243317  0.108078  0.192165 -0.118429   
MeTr -0.237846 -0.040311 -0.606530  0.465550  0.718556 -0.148726  0.377106   
MoTr -0.667909 -0.216138  0.466011  0.118819  0.207032  0.298971 -0.212882   
RiRi -0.311236  0.195006  0.234262  0.741436  0.218471  0.257728  0.259866   
MoFo -0.313909 -0.285269  0.095813  0.158044  0.145419  0.369778 -0.511182   
Mmof -0.476609  0.142926  0.064052  0.505577  0.251152  0.320710  0.034457   
MoRi -0.379376 -0.066997 -0.191375  0.649681  0.294435  0.046285  0.271691   
MeRi -0.132961 -0.329820  0.129914 -0.354336 -0.095571 -0.358480 -0.362803   
Ri   -0.563191 -0.398614  0.265614 -0.027620 -0.129102 -0.293206  0.330743   
Comp -0.267206  0.311151 -0.417138 -0.924776  0.461390  0.078602  0.405451   

          MoTr      RiRi      MoFo      Mmof      MoRi      MeRi        Ri  \
TrRi -0.350846 -0.124972  0.235450  0.137425 -0.531965  0.264298  0.166439   
RiTr -0.118040 -0.444297  0.209074  0.092889 -0.012311  0.233756  0.050772   
Plu   0.095562 -0.265006  0.323443  0.318363 -0.268569 -0.447416  0.243699   
Ttra  0.115430 -0.028899  0.554424  0.219523  0.330389  0.093097  0.464091   
Ttrb -0.201036  0.315952  0.071989  0.547407 -0.077660  0.216503 -0.664574   
Tr    0.017604 -0.310293  0.374774  0.242819 -0.339650 -0.126303 -0.043444   
MeTr  0.278993 -0.491082  0.079382 -0.216052  0.582619  0.145657 -0.663608   
MoTr -0.181154 -0.395986  0.243083  0.133172 -0.161037 -0.140548  0.324216   
RiRi -0.201408 -0.170462  0.017236  0.197097  0.152464 -0.464821  0.192691   
MoFo  0.201035 -0.281086  0.427540  0.252716 -0.123318 -0.092667  0.153888   
Mmof -0.035058 -0.185531  0.007523  0.179930 -0.369754 -0.202725  0.165776   
MoRi -0.137480 -0.448678  0.060271  0.170447 -0.389747 -0.375868  0.385047   
MeRi -0.258862  0.257830  0.075436  0.549342  0.018500 -0.363107 -0.432196   
Ri   -0.129493 -0.244294  0.558252  0.170400 -0.172005 -0.000969  0.099044   
Comp -0.145702 -0.226082 -0.190659  0.048967  0.157962  0.118295 -0.517191   

          Comp  
TrRi -0.109050  
RiTr -0.083759  
Plu  -0.026358  
Ttra  0.069246  
Ttrb  0.217016  
Tr    0.013585  
MeTr  0.802352  
MoTr -0.157806  
RiRi -0.134792  
MoFo  0.135851  
Mmof -0.063473  
MoRi -0.227175  
MeRi  0.014156  
Ri   -0.104070  
Comp -0.225768

In [181]:
df_free_evolution_dict = {}
for subject in subjects:
    np_matrix_initial = df_weights_dict[subject].to_numpy()
    np_matrix = np_matrix_initial
    df_free_evolution_dict[subject] = pd.DataFrame(index = ["TrRi","RiTr","Plu","Ttra","Ttrb","Tr","MeTr","MoTr","RiRi","MoFo","Mmof","MoRi","MeRi","Ri","Comp"])
    for i in range(0,50):
        np_matrix = np.matmul(np_matrix, np_matrix_initial)
        sum_np = np.sum(np_matrix, axis=0) #1
        df_free_evolution_dict[subject]["Epoch "+ str(i)] = list(sum_np)
        np_matrix = np.divide(np_matrix, sum_np) # divide() is division by row

    df_free_evolution_dict[subject] = df_free_evolution_dict[subject].T

/tmp/ipykernel_20916/3387159264.py:10: RuntimeWarning:

divide by zero encountered in divide

/home/davide/Desktop/LAVORO/SEMEION/neural-network-with-fuzzified-inverter/env/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/tmp/ipykernel_20916/3387159264.py:10: RuntimeWarning:

divide by zero encountered in divide

/home/davide/Desktop/LAVORO/SEMEION/neural-network-with-fuzzified-inverter/env/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/tmp/ipykernel_20916/3387159264.py:10: RuntimeWarning:

divide by zero encountered in divide

/home/davide/Desktop/LAVORO/SEMEION/neural-network-with-fuzzified-inverter/env/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/tmp/ipykernel_20916/3387159264.py:10: RuntimeWarning:

divide by zero encountered in divide

/home/davide/Desktop/LAVORO/SEMEION/neural-netwo

In [182]:
df_free_evolution_dict["soggetto_1"].head()

TrRi      RiTr       Plu      Ttra      Ttrb        Tr      MeTr  \
Epoch 0  3.350551 -0.042014 -3.747826 -2.982141  0.949347  2.503390 -3.816050   
Epoch 1 -5.960241 -2.167177  0.061604  2.579468  3.227234  1.460613  0.462245   
Epoch 2 -5.960241 -2.167177  0.061604  2.579468  3.227234  1.460613  0.462245   
Epoch 3 -5.960241 -2.167177  0.061604  2.579468  3.227234  1.460613  0.462245   
Epoch 4 -5.960241 -2.167177  0.061604  2.579468  3.227234  1.460613  0.462245   

             MoTr      RiRi      MoFo      Mmof      MoRi      MeRi        Ri  \
Epoch 0  3.919131  1.706469  1.204225  1.325109  2.239405  0.256543 -2.397361   
Epoch 1 -1.050456 -3.042887  3.047215  3.044444 -1.204083 -1.142820 -0.075350   
Epoch 2 -1.050456 -3.042887  3.047215  3.044444 -1.204083 -1.142820 -0.075350   
Epoch 3 -1.050456 -3.042887  3.047215  3.044444 -1.204083 -1.142820 -0.075350   
Epoch 4 -1.050456 -3.042887  3.047215  3.044444 -1.204083 -1.142820 -0.075350   

             Comp  
Epoch 0  3.134337  
Epoch 1  0.119957  
Epoch 2  0.119957  
Epoch 3  0.119957  
Epoch 4  0.119957

In [ ]:
# nomal matrix: 
# row output of a dime3nsion
# column input of a dimension

# transpose matrix:
# row input of a dimension
# column output of a dimension

In [183]:
# create test np matrix 3x3
np_matrix_test = np.array([[0.1,-0.2,0.3],[0.4,0.5,0.6],[0.7,-0.8,0.9]])
np_matrix_test

array([[ 0.1, -0.2,  0.3],
       [ 0.4,  0.5,  0.6],
       [ 0.7, -0.8,  0.9]])

In [184]:
# sum over rows
sum_np_test = np.sum(np_matrix_test, axis=1)
sum_np_test

array([0.2, 1.5, 0.8])

In [185]:
# divide each row by the sum of the row
np_matrix_test = np.divide(np_matrix_test, sum_np_test)
np_matrix_test

array([[ 0.5       , -0.13333333,  0.375     ],
       [ 2.        ,  0.33333333,  0.75      ],
       [ 3.5       , -0.53333333,  1.125     ]])

In [186]:
# for every subject, plot the free evolution of the weights using plotly express
for subject in subjects:
    fig = px.line(df_free_evolution_dict[subject].iloc[:100], title="Free evolution of the weights for subject {}".format(subject))
    fig.show()

In [187]:
# display values of the last row for every subject
for subject in subjects:
    df_free_evolution_dict[subject]

In [188]:
# display values of the last row for every subject
for subject in subjects:
    print("Subject: {}".format(subject))
    print(df_free_evolution_dict[subject].iloc[-1].var())

Subject: soggetto_1
nan
Subject: soggetto_2
nan
Subject: soggetto_3
nan
Subject: soggetto_6
623.6064406622024
Subject: soggetto_7
nan
Subject: soggetto_8
nan
